# Generated by Django 4.1.3 on 2022-11-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_devise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.products'),
        ),
    ]
