# Generated by Django 4.1.3 on 2022-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devise',
            name='name',
            field=models.CharField(choices=[('CFA', 'Francs CFA'), ('USD', 'Dollars'), ('EUR', 'Euros')], default='CFA', max_length=3),
        ),
    ]
